### ISSUE TITLE
SkinsRestorer issue

### ISSUE THREAD

**Issue by SteveTheEngineer** [ZombieStriker/WorldChangeScreenRemover#12]
When I try to change my skin using SkinsRestorer, nothing happens.
But when I remove WCSR, it's working.

**Comment by xCustomWorld** [comment]
Can confirm with CMI.

**Comment by ZombieStriker** [comment]
Does this issue still occur on the newest update?

**Comment by SteveTheEngineer** [comment]
The incompatibility is fixed. Closed
