### ISSUE TITLE
Feature request: message in transit

### ISSUE THREAD

**Issue by SlimeDog** [ZombieStriker/WorldChangeScreenRemover#2]
Please implement a configurable message to be sent to the player. Transport still takes a few seconds, so I would like to display a message. I prefer title/subtitle, but others may have different ideas. There must be a placeholder for the target world, and probably should be one for the world being exited, in case someone wants to include them in the message.

**Comment by ZombieStriker** [comment]
I may add this in a future update.

**Comment by SlimeDog** [comment]
Supporting PlaceholderAPI (or similar) would be even better. For example:
> %multiverse_world_alias%

**Comment by ZombieStriker** [comment]
I just added placeholder support. You can now get where the user is coming from and where they are going to using %WCSR_From% and %WCSR_To% respectively. 

Titles are not enabled by default. To enable them, set "enableTitles" to true in the config.

**Comment by SlimeDog** [comment]
That was fast! Thanks.
