### ISSUE TITLE
Feature request: reload command

### ISSUE THREAD

**Issue by SlimeDog** [ZombieStriker/WorldChangeScreenRemover#3]
Please implement a **wcsr** alias and a **wcsr reload** command (from the console and in-game).

**Comment by ZombieStriker** [comment]
I may add this in a future update.

**Comment by SlimeDog** [comment]
Thanks. It would make testing a lot smoother.

**Comment by ZombieStriker** [comment]
It was extremely simple to add. Update 1.0.5 now contains this and alias support.
