### ISSUE TITLE
Feature request: MV alias support

### ISSUE THREAD

**Issue by SlimeDog** [ZombieStriker/WorldChangeScreenRemover#5]
_%WCSR_From%_ and _%WCSR_To%_ work great, but worldname aliases would be better. Unfortunately, _%multiverse_world_alias%_ cannot evaluate as both the _from_ and the _to_. Please consider adding support for
> %WCSR_From_Alias%
> %WCSR_To_Alias%

each of which would reflect the appropriate Multiverse-Core (or perhaps other multi-world system) alias, and revert appropriately if the relevant alias were empty.

**Comment by ZombieStriker** [comment]
World names from WCSR now support world aliases. The existing placeholders will now use the aliases by default (if any exist)

**Comment by SlimeDog** [comment]
Spigot 1.12.2
WCSR 1.0.5

Reload works great, but I am not seeing the MV aliases. I configured
```
enableTitles: true
Title: arriving %WCSR_To% ...
SubTitle: from %WCSR_From%
```
but I see the full world names.
```
arriving world_test ...
from world_lobby
```

Multiverse-Core/worlds.yml
```
worlds:
...
  world_lobby:
    ==: MVWorld
    hidden: 'false'
    alias: lobby
...
  world_test:
    ==: MVWorld
    hidden: 'false'
    alias: test
```
