### ISSUE TITLE
Fade-in/out doesn't

### ISSUE THREAD

**Issue by SlimeDog** [ZombieStriker/WorldChangeScreenRemover#7]
Spigot 1.12.2
WCSR 1.0.7C

With configuration
```
enableTitles: true
Title: arriving %WCSR_To% ...
SubTitle: from %WCSR_From%
TitleFadeIn-In-Seconds: 0.5
TitleStay-In-Seconds: 5.0
TitleFadeOut-In-Seconds: 0.5
```
I see no fade-in or fade-out.

Please do not append release numbers with B, C, etc. Just bump the version. (And remember to bump in plugin.yml as well.)

**Comment by ZombieStriker** [comment]
Well, you should not, you set the fade-in and fade-out to 0.5, a half a second. There should be close to no fading with those values.

If you want fading, increase those values.

(I've also tested it, and the fading _does work_)

**Comment by SlimeDog** [comment]
I didn't set anything. Those are the default values when the plugin is updated.

**Comment by SlimeDog** [comment]
Increasing the timers works fine. I'm using
```
TitleFadeIn-In-Seconds: 2.0
TitleStay-In-Seconds: 2.0
TitleFadeOut-In-Seconds: 2.0
```
